### ISSUE TITLE
RabbitMQ empty log file

### ISSUE THREAD

**Issue by jworcestBAH** [fedspendingtransparency/data-act-broker-backend#37]
Some number of users may be affected by a known RabbitMQ issue on Windows where the program does not run but the log files remain empty.  Pivotal's response to this issue: https://groups.google.com/forum/#!topic/rabbitmq-users/6nN-ORsl_gw

**Comment by bsweger** [comment]
Update: 10/28...clarifying that this issue affects folks who want to do a local broker install on Windows 8. It doesn't affect the hosted broker.

**Comment by dpb-bah** [comment]
Note: RabbitMQ is no longer used. Closing issue.
