### ISSUE TITLE
Missing CSV files

### ISSUE THREAD

**Issue by colinalexander** [fedspendingtransparency/data-act-broker-backend#545]
Files required for initializing the broker (e.g. cgac.csv, object_class.csv, program_activity.csv) should be placed  in a `data` folder and included in the repo (or at least provide a link to where the required files can be downloaded).

**Comment by alburde1** [comment]
These files actually do exist. If you look in dataactvalidator/config you'll see example_cgac, example_object_class, and example_program_activity. Simply copy-paste them into the correct names just like you would the other example config files.

**Comment by colin1alexander** [comment]
It is only obvious if you know where to look. When following the installation documentation, it should either be noted that the files need to be renamed or else the files themselves should drop the "example_" prefix.
